# Generated by Django 4.1.6 on 2023-03-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_show_temperature', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cityNameDB',
        ),
    ]
